# Generated by Django 4.2 on 2025-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavebalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='remaining_days',
            new_name='remaining_balance',
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='leave',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
