# Generated by Django 4.2 on 2025-07-19 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_rename_remaining_days_leavebalance_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 19, 16, 6, 9, 236333)),
            preserve_default=False,
        ),
    ]
